### ISSUE TITLE
How to have the Monterey style Firefox for Windows?

### ISSUE THREAD

**Issue by HuyHung1408** [vinceliuice/WhiteSur-firefox-theme#1]
I know that I need to run some commands but can you explained more details how to use this. Big thanks.

**Comment by vinceliuice** [comment]
use this: https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS

**Comment by vinceliuice** [comment]
My version is only for Linux

**Comment by HuyHung1408** [comment]
ok thanks anyways
