### ISSUE TITLE
line when autohide

### ISSUE THREAD

**Issue by miloumeeloo** [vinceliuice/WhiteSur-firefox-theme#13]
Not really an issue and maybe not from your side.
I try to combine your theme with firefox-ui-fix. Latest releases for both.
I use the autohide option for bookmarkbar and tabbar but it keeps a line for each under the toolbar when hiding.
I didn't manage to find the part of your code which could produce that.
Maybe you could enlighten me?

![firefox](https://user-images.githubusercontent.com/57871403/218270754-61207658-c681-456b-af45-3dd9462ed227.png)

**Comment by miloumeeloo** [comment]
I'm using the monterey-alt theme with the tabbar at the bottom under the bookmarkbar.
Sorry for the lack of precision in my previous description.
I tried to apply your changes on toolbox-alt.css without success.

**Comment by vinceliuice** [comment]
Now fixed

**Comment by miloumeeloo** [comment]
I still have this two lines when the bars hide.

![firefox](https://user-images.githubusercontent.com/57871403/219704569-eade533c-9731-4de4-a0fb-aed454ab6242.png)
