### ISSUE TITLE
Does it work with nightly ?

### ISSUE THREAD

**Issue by mesziman** [vinceliuice/WhiteSur-firefox-theme#18]
I tried on nightly, the tabs remained in the menubar for Monterey, for alt design they remained on top of the url .
Is it an issue in my side?

![image](https://user-images.githubusercontent.com/4874388/229136773-1117ca3d-b945-4cf9-bc47-07af9c3cf741.png)

Thanks and regards,
Gabor

**Comment by LosEagle** [comment]
Can confirm on beta 113.0b3
