### ISSUE TITLE
Firefox v113 breaks window buttons and tab bar's positions

### ISSUE THREAD

**Issue by soulthunk** [vinceliuice/WhiteSur-firefox-theme#23]
![Screenshot_2023-05-09_19-30-53](https://github.com/vinceliuice/WhiteSur-firefox-theme/assets/24778461/d1ec87c0-5a08-4e99-8598-8c82950ebc49)

With the recent update to Firefox, the browser has removed moz-box, which I assume is the cause of the broken positioning of the tabs list and the window buttons. 

EDIT: The suggested fix on #18 works.

**Comment by lilbudek** [comment]
> Fixed

the problem is solved, but it would be great if the tab names were centered, as before
