### ISSUE TITLE
How can I change tab bar height? I think on README.md screenshot it is smaller

### ISSUE THREAD

**Issue by playXE** [vinceliuice/WhiteSur-firefox-theme#27]
![image](https://github.com/vinceliuice/WhiteSur-firefox-theme/assets/41432780/054e7613-a5cd-43ce-b433-58f776eef4fa)

**Comment by vinceliuice** [comment]
Download the last update on github and try again

**Comment by playXE** [comment]
> Download the last update on github and try again

That is the last update on GH. I've cloned it just before the screenshot :D

**Comment by vinceliuice** [comment]
![截图 2023-06-12 17-40-11](https://github.com/vinceliuice/WhiteSur-firefox-theme/assets/7604295/dc759bf9-0e36-46e4-9fb4-978f69bf9e45)
This is on my Firefox 114.0.1

**Comment by playXE** [comment]
For some reason Monterey theme looks fine. I'll just stick to it probably
