### ISSUE TITLE
How can I remove this theme?

### ISSUE THREAD

**Issue by tahdiislam** [vinceliuice/WhiteSur-firefox-theme#32]

**Comment by AdamXweb** [comment]
Duplicate of #29

See https://github.com/vinceliuice/WhiteSur-firefox-theme/issues/29#issuecomment-1702949453

**Comment by tahdiislam** [comment]
> Duplicate of #29
> 
> See [#29 (comment)](https://github.com/vinceliuice/WhiteSur-firefox-theme/issues/29#issuecomment-1702949453)

Thanks.
