### ISSUE TITLE
Can't make compact tabs work

### ISSUE THREAD

**Issue by ghost** [vinceliuice/WhiteSur-firefox-theme#36]
I managed to get the Safari theme working by manually downloading the code from the /AdamXweb/WhiteSurFirefoxThemeMacOS/Github, but I can't get the compact tabs to work in this one here from vince. 

All I did was copy and paste the chrome folder contents from the AdamXweb Github to get Safari UI working, but I don't know how to make this compact UI work from this specific github repo here (the one from Vince).

I also emailed Adam about something else, so please get back to me on that as well

Thanks!

**Comment by AdamXweb** [comment]
Do you mean the Monterey style?

What OS and version of Firefox are you using?

**Comment by CasanovaSan** [comment]
> Do you mean the Monterey style?
> 
> What OS and version of Firefox are you using?

Most likely drkhero is on Windows, and as well as latest firefox version
