### ISSUE TITLE
URL Bar acting like titlebar

### ISSUE THREAD

**Issue by grav3yardshawty** [vinceliuice/WhiteSur-firefox-theme#43]
i'm having an issue where the url bar seems to also think its the titlebar, as in im able to grab and move the window by dragging it, and most annoyingly, i can't double click it to select text without maximizing or unmaximizing the window. im not sure if this is an issue with my KDE Plasma, but this only happens when i have the theme on

edit: for clarification, im using the monterey option

**Comment by Hesham1902** [comment]
i have the same issue

**Comment by Hesham1902** [comment]
> i have the same issue

i tried this solution and it worked with me you can navigate to userChrome.css file inside firefox-themes directory
and add this lines

`#urlbar,
#urlbar-container,
#nav-bar-customization-target {
    -moz-window-dragging: no-drag !important;
}

#urlbar {
    user-select: text !important;
    -moz-user-select: text !important;
}

#nav-bar,
#navigator-toolbox,
#TabsToolbar {
    -moz-window-dragging: no-drag !important;
}
`
