### ISSUE TITLE
Update broke it

### ISSUE THREAD

**Issue by Elitemmx** [vinceliuice/WhiteSur-firefox-theme#45]
The update just broke the theme

**Comment by Elitemmx** [comment]
Firefox have been updated and broke the theme

**Comment by thienpow** [comment]
the close/minimize/maximize button not staying at top, but gone to tabbar

**Comment by bilal-algorithms** [comment]
yeah, anything new?

**Comment by thienpow** [comment]
the theme that this repo is referring has the fix done:
https://github.com/rafaelmardojai/firefox-gnome-theme/commit/76f4802685d752c8865144a179acaa9cdf240a93

now we just wait this repo owner to update...

**Comment by bilal-algorithms** [comment]
> the theme that this repo is referring has the fix done: [rafaelmardojai/firefox-gnome-theme@76f4802](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/76f4802685d752c8865144a179acaa9cdf240a93)
> 
> now we just wait this repo owner to update...

could I just update the files manually?

**Comment by vinceliuice** [comment]
Fixed now
