### ISSUE TITLE
Even after update, titlebar is not placed properly

### ISSUE THREAD

**Issue by bilal-algorithms** [vinceliuice/WhiteSur-firefox-theme#47]
![Screenshot From 2024-11-29 21-54-16](https://github.com/user-attachments/assets/6fc2efc4-965a-4cd9-aa06-52270222e738)
the titlebar is placed on the right, but I want it on the left what should I do?

**Comment by tetam01** [comment]
You have to edit the file csd.css (~/.firefox/themes/Monterey/parts/csd.css). Got to /* Window buttons box */ and replace right with left. At the end it should look like this:

/* Window buttons box */
:root[tabsintitlebar] #nav-bar .titlebar-buttonbox-container,
:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container,
:root[tabsintitlebar] #titlebar-buttonbox-container,
:root[tabsintitlebar][inFullscreen] #window-controls {
	-moz-appearance: none !important;
	padding: 0 3px 0 4px;
	position: absolute !important;
	**left**: 8px;
	top: 0;
	display: block !important;

**Comment by vinceliuice** [comment]
Fixed now
