### ISSUE TITLE
Hide window buttons when maximized not working

### ISSUE THREAD

**Issue by TheUnawsomeGuy** [vinceliuice/WhiteSur-firefox-theme#48]
![image](https://github.com/user-attachments/assets/7e0b37c6-aef6-4269-8edb-10af6b9ff8d6)

Applying the hide window button when maximized css causes the buttons to still appear but shifting the entire toolbar, causing an overlap.

**Comment by vinceliuice** [comment]
What about now ?

**Comment by TheUnawsomeGuy** [comment]
Working now, thank you :+1:
