### ISSUE TITLE
Enhancement on the vertical tabs

### ISSUE THREAD

**Issue by dhra** [vinceliuice/WhiteSur-firefox-theme#49]
Mozilla is bringing vertical tabs for users. The icons with all templates are misaligned.

![image](https://github.com/user-attachments/assets/e81559f3-8013-497d-91d0-50f55d99d329)

To reproduce the issue, you can download Firefox Nightly. Go to `about:config` and set `sidebar.revamp` to true.

**Comment by dhra** [comment]
**The first issue** is that the Flat theme needs a padding for tabs:
```bash
./tweaks.sh -f flat
```

![image](https://github.com/user-attachments/assets/6fb6bb25-6faa-44ff-9ee1-6cd7addbd06f)


Monterey looks good: 

![image](https://github.com/user-attachments/assets/f9da50cf-c32c-40e2-bff0-f2617799d144)

**The second issue** is that window buttons are missed

Firefox with the default theme
![image](https://github.com/user-attachments/assets/03c2cd96-5b2e-4a74-b05d-847bd12669b3)


Firefox with the all variants of the WhiteSur theme

![image](https://github.com/user-attachments/assets/3ffae2c9-90aa-429c-a6eb-f9de08501e42)

**Comment by vinceliuice** [comment]
now it's ok

**Comment by vinceliuice** [comment]
If you active this `hide-window-buttons.css` windows button will gide when  maximized

**Comment by dhra** [comment]
> If you active this `hide-window-buttons.css` windows button will hide when maximized

- `hide-window-buttons.css` is not enabled and the window is not fully maximized. There are no window buttons.

- I'm using the flat theme. Then opened `omgubuntu.org` in a new container. The container boarder line is not aligned properly.

![image](https://github.com/user-attachments/assets/39bd66f5-f2ae-4872-9028-988989e3c5bb)
