### ISSUE TITLE
address bar extending way too far when clicked 

### ISSUE THREAD

**Issue by Gogoseit2020** [vinceliuice/WhiteSur-firefox-theme#51]
![image](https://github.com/user-attachments/assets/6bc33577-65f8-4d17-b779-bc11e0b46ebe)
installed the theme without many issues, but for some reason whenever I type in the address bar it extends all the way to the right, and it's really annoying, I am re-installing because for some reason it suddenly stopped working after a while (entire theme broke after firefox updated) 
any way to fix this?

**Comment by vinceliuice** [comment]
this should be fixed，download the last update and try again

**Comment by Gogoseit2020** [comment]
Thank you for the quick response and patch, it is working now
