### ISSUE TITLE
Monterey mode not working

### ISSUE THREAD

**Issue by EuriNaiz** [vinceliuice/WhiteSur-firefox-theme#6]
It just fails, and installs the WhiteSur theme.

**Comment by AdamXweb** [comment]
What install command did you use?

**Comment by AdamXweb** [comment]
Could you try: `./install.sh -m`

The install script seems to be tweaked from the master repo, but the readme hasn't updated to look for the monterey case. Fixing with a PR

**Comment by EuriNaiz** [comment]
Thank you, everything seems to be working, it installed fine with the last command.
